app = "japanese-tutor"
primary_region = "sjc"

[build]
  builder = "paketobuildpacks/builder:base"

[env]
  PORT = "8080"
  PYTHONPATH = "/app"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[deploy]
  release_command = "python -m pip install uvicorn"

[processes]
  app = "uvicorn app.main:app --host=0.0.0.0 --port=8080"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
